// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUAcNNyoxUW2st7-esW9XtK7rE9sRgccg',
    appId: '1:142775040760:web:d4ec45cddeb7c6b9bb590d',
    messagingSenderId: '142775040760',
    projectId: 'codepie-9f0b3',
    authDomain: 'codepie-9f0b3.firebaseapp.com',
    storageBucket: 'codepie-9f0b3.appspot.com',
    measurementId: 'G-BSV962S1KX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPF3UKWSFjdmH3Ips9Cwn8hA4uAYcSdUg',
    appId: '1:142775040760:android:dc06e7cd348090ebbb590d',
    messagingSenderId: '142775040760',
    projectId: 'codepie-9f0b3',
    storageBucket: 'codepie-9f0b3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvJFRmVsfc4UfCnak5E7-9C8jWPXwpbO4',
    appId: '1:142775040760:ios:331670cc253cc66cbb590d',
    messagingSenderId: '142775040760',
    projectId: 'codepie-9f0b3',
    storageBucket: 'codepie-9f0b3.appspot.com',
    iosBundleId: 'com.example.codepie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvJFRmVsfc4UfCnak5E7-9C8jWPXwpbO4',
    appId: '1:142775040760:ios:331670cc253cc66cbb590d',
    messagingSenderId: '142775040760',
    projectId: 'codepie-9f0b3',
    storageBucket: 'codepie-9f0b3.appspot.com',
    iosBundleId: 'com.example.codepie',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBUAcNNyoxUW2st7-esW9XtK7rE9sRgccg',
    appId: '1:142775040760:web:b7e17f4ef53f319fbb590d',
    messagingSenderId: '142775040760',
    projectId: 'codepie-9f0b3',
    authDomain: 'codepie-9f0b3.firebaseapp.com',
    storageBucket: 'codepie-9f0b3.appspot.com',
    measurementId: 'G-6VGJRXVGLS',
  );
}
